# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    container.autowiring.strict_mode: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\Services\:
        resource: '../../src/AppBundle/Services'
        public: true

    Nines\BlogBundle\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: postNavMenu, alias: posts}
            - { name: knp_menu.menu_builder, method: pageNavMenu, alias: pages}

    Nines\UserBundle\Menu\Builder:
        tags:
            - { name: knp_menu.menu_builder, method: userNavMenu, alias: user}

    AppBundle\Menu\Builder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: main}

    AppBundle\Services\FileUploader:
        public: true
        arguments: ['%btd.media_upload_path%']

    AppBundle\Services\Thumbnailer:
        arguments:
            $width: '%btd.thumbnail_width%'
            $height: '%btd.thumbnail_height%'

    AppBundle\EventListener\FileUploadListener:
        public: true
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postLoad }
